// post thread
export const POST_THREAD_REQUEST = 'POST_THREAD_REQUEST';
export const POST_THREAD_SUCCESS = 'POST_THREAD_SUCCESS';
export const POST_THREAD_FAIL = 'POST_THREAD_FAIL';

// list thread
export const LIST_THREAD_REQUEST = 'LIST_THREAD_REQUEST';
export const LIST_THREAD_SUCCESS = 'LIST_THREAD_SUCCESS';
export const LIST_THREAD_FAIL = 'LIST_THREAD_FAIL';
export const LIST_THREAD_RESET = 'LIST_THREAD_RESET';